#+TITLE:Practice: Summary statistics
#+AUTHOR: [YourName]
#+SUBTITLE: Applied math for data science (DSC 482/MTH 445) Fall 2022
#+OPTIONS: toc:nil num:1 ^:nil
#+STARTUP: overview hideblocks indent inlineimages
#+PROPERTY: header-args:R :session *R* :results output
* README

  - Practice for "Summary statistics" ([[https://github.com/birkenkrahe/dsmath/blob/main/org/4_summary_stats.org][GitHub]])
  - Source: chapter 13.2 by Davies, 2016 (modified)
  - Emacs + ESS + Org-mode and R must be installed
    
* TODO Identify yourself

  - Update the ~#+AUTHOR:~ information in the header
  - Put your cursor on the headline of this section, and type ~S <LEFT>~
    until you see ~DONE~ instead of ~TODO~ next to the title.
  - Perform this last step each time you complete a section.

* TODO Proportions

The built-in ~quakes~ data set gives the locations of 1000 seismic
events of MB > 4.0. The events occurred in a cube near Fiji
since 1964.

Obtain, rounded to two decimal places, the proportion of seismic
events in the ~quakes~ data frame that occurred at a depth of 300 km
or deeper.

* TODO Mean and median

From the ~quakes~ data set, calculate the mean and median magnitudes of
the events that occurred at a depth of 300 km or deeper.

* TODO Identify statistical variables

The built-in ~InsectSprays~ data set contains data on the number of insects
found on various agricultural units, as well as the type of spray
used on each unit.

Study the help file to get an idea of R's representation of the two
variables:

- Variable ??? is a ??? variable

- Variable ??? is a ??? variable ???

* TODO Mode

From the ~InsectSprays~ data set, calculate the modes of the
distribution of insect counts, regardless of spray type.

* TODO Counts

In the ~InsectSprays~ data set, use ~tapply~ to report the total insect
counts by each spray type.

